-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM 
(SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
FROM FIRST_HALF
GROUP BY FLAVOR) FH
JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER) TOTAL
FROM JULY
GROUP BY FLAVOR) J
ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL + J.TOTAL DESC
LIMIT 3

