-- 코드를 입력하세요
SELECT A.MEMBER_NAME,RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN (
SELECT MF.MEMBER_ID,MF.MEMBER_NAME,RANK() OVER(ORDER BY RC.CNT DESC) AS RANKING
FROM
(SELECT *,COUNT(REVIEW_ID) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID) RC
JOIN MEMBER_PROFILE MF
ON MF.MEMBER_ID = RC.MEMBER_ID
    ) A
ON RR.MEMBER_ID = A.MEMBER_ID
WHERE A.RANKING = 1
ORDER BY RR.REVIEW_DATE

    